### ISSUE TITLE
can it sync database across my devices

### ISSUE THREAD

**Issue by jots** [PositiveSumNet/SocialAssistant#5]
nice tool, thanks for making it.
can the database sync across multiple computers?

**Comment by scafaria** [comment]
Thanks! Yes, definitely on roadmap. An export/import feature was just added (for manual backup/restore). That release was submitted to the app store. Hopefully it'll be approved by tomorrow. 

The plan is to evolve that into an automated sync, probably with a personal/private GitHub repo as the back-end. I think the most exciting sync use case would be to support a mobile experience (as opposed to just across two Chrome extensions). If the user's personal GitHub is the back-end, I figure the next logical step is to use a GitHub template to auto-create for the user a GitHub Pages (static web application). From *there* the user has a GitHub back-end powering a web/mobile (PWA) app. At that point, the possibilities are [endless](https://scafaria.com/prosocial-micro-blogging-at-scale-7c4d45c063fd). The Whosum PossumID (example [here](https://whosum.com/t/scafaria)) can be used to prove ownership of data files (and associate with a public/private key pair) to facilitate secure, distributed sharing scenarios.

**Comment by jots** [comment]
sounds great!  Thank you!

**Comment by scafaria** [comment]
The export feature currently released now allows for selective export fyi. True "sync" remains on roadmap.

**Comment by scafaria** [comment]
This is now merged into the master branch and will be released soon... along with tweet recording ;-)
