### ISSUE TITLE
Tooltip for Mastodon settings cog

### ISSUE THREAD

**Issue by andypiper** [PositiveSumNet/SocialAssistant#6]
If I mouseover the gear icon by the `w/ Mastodon URL` label, it shows a tooltip about setting page size.
 
![image](https://user-images.githubusercontent.com/552452/230432093-78a3228d-efc8-44c0-a1fd-a867febb5903.png)

I think this is unintended (the tooltip is similar but not the same as the one for the gear icon by the numbered paging options).

Code is at https://github.com/PositiveSumNet/SocialAssistant/blob/038c21347a190c9a30578559afd3872c0e28c29b/index.html#L90

Opening as an issue rather than sending a PR as I am not completely sure what the developer's intent is 👍🏻 thanks!

**Comment by scafaria** [comment]
Good catch. Thank you. Will fix.

**Comment by scafaria** [comment]
Pushed commit; Slated for 1.0.4
