### ISSUE TITLE
Suggestion: show version in UI

### ISSUE THREAD

**Issue by andypiper** [PositiveSumNet/SocialAssistant#7]
I see that v1.0.2 was released, but is not in the Chrome store yet (I just installed the extension today, and I see in the Chrome extensions panel that this is v1.0.1)

Tiny suggestion: show the current installed / running version of the extension in the footer of the page, where you also have things like the SQLite DB version. Saves on having to separately open the Chrome extensions panel to check, when the fastest way into the extension is to click on the toolbar icon.

**Comment by scafaria** [comment]
Pushed commit; Slated for 1.0.4
